[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1.39", features = ["full"] }



[dependencies.async-std]
version = "1.6"
features = ["attributes"]

